title: eacxns
email: email@eacxns.com
description: Economics student at UChicago. I enjoy crypto, Boston sports, Manchester United, skiing, and the internet.
url: "https://eacxns.com"
twitter: eacxns

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
highlighter: rouge
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
