title: EACXNS
email: email@eacxns.com
description: eac's website
url: "https://eacxns.com"
twitter: eacxns

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed